version: "3.0"

services:

  hub:
    build:
      context: ./jupyterhub
      dockerfile: Dockerfile.hub
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    volumes:
      - "./jupyterhub/jupyterhub_config.py:${HUB_CONFIG_PATH}"
      - "./jupyterhub/secrets/jupyterhub-key.pem:${SSL_KEY_PATH}"
      - "./jupyterhub/secrets/jupyterhub-crt.pem:${SSL_CERT_PATH}"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "data:${DATA_VOLUME_CONTAINER}"
    ports:
      - "443:443"
    environment:
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      DOCKER_NOTEBOOK_IMAGE: ${LOCAL_NOTEBOOK_IMAGE}
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
      SSL_KEY: ${SSL_KEY_PATH}
      SSL_CERT: ${SSL_CERT_PATH}
    env_file:
      - jupyterhub/secrets/oauth.env
    command: >
      jupyterhub -f ${HUB_CONFIG_PATH}


  grafana:
    image: grafana/grafana-oss:9.1.1
    restart: always
    container_name: grafana
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=org-snapshot
    volumes:
      - grafana-data:/var/lib/grafana
      - "/home/josef/jupyterhub/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "/home/josef/jupyterhub/grafana/grafana-plugins/:/var/lib/grafana/plugins"
    ports:
      - "8080:3000"
    user: "472"
    depends_on:
      - grafana-server

  grafana-server:
    build:
      context: ./grafana/microserver
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./grafana/microserver/main.py:/home/main.py"
    ports:
      - "8000:8000"


  stream:
    build:
      context: ./stream_data
      dockerfile: Dockerfile
    networks:
      - "public"
    restart: always
    container_name: stream
    volumes:
      - "./stream_data/src:/home"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"

  # mysql:
  #   image: mysql
  #   ports:
  #     - "8000:3306"
  #   volumes:
  #     - ~/apps/mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_USER=admin
  #     - MYSQL_DATABASE=db


volumes:
  data:
    external:
      name: ${DATA_VOLUME_HOST}
  db:
    external:
      name: ${DB_VOLUME_HOST}
  grafana-data:

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
  public:
    external:
      name: public
        