import requests as rq
from flask import Flask, Response
import dbrepo as db
from datetime import datetime
from flask import request

# Flask constructor takes the name of
# current module (__name__) as argument.
app = Flask(__name__)
 
client = db.Client('jtaha','pw',verifyTLS=False)

@app.route('/<cid>/<dbid>',methods=['POST'])
def snapshot(cid,dbid):
    
    query = request.data.decode('ascii')
    print(query,'\n')

    id, _ = client.query_by_statement(cid,dbid,query)

    now = datetime.now()

    body = { 'qid': id, "title": "Grafana QID",
        'description': "This Query Identifier is generated by Grafana.",
        'publication_year': str(now.year), 'publication_month': str(now.month),
        'publication_day': str(now.day),
        'visibility': "everyone",
        'doi': None,
        'creators': [
          {
            'name': "Grafana",
            'affiliation': "DBRepo",
            'orcid': None
          }
        ],
        'related_identifiers': []
      }

    auth = {
        'Authorization': client.token,
        'Content-Type': 'application/json'
    }

    print(body)

    res = rq.post(f'https://dbrepo.ossdip.at/api/container/{cid}/database/{dbid}/identifier',json=body,headers=auth, verify=False)
    print(res.content)
    print(res.text)
    id = res.json()['id']
    resp = Response(f'http://dbrepo.ossdip.at/pid/{id}')
    resp.headers['Access-Control-Allow-Origin'] = '*'
    return resp
    

if __name__ == '__main__':
    app.run(host='0.0.0.0',port=8000,debug=True)